# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'ChartsBootstrapDemo' do
    pod 'ChartsBootstrap', :path => '../'
end

target 'ChartsBootstrapDemoTests' do

end

